services:
  postgres:
    image: postgres:18
    container_name: pg-sec-test
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "16432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./pgconf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pgconf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./certs:/certs:ro
      - ./init:/docker-entrypoint-initdb.d:ro
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgbouncer_pwd:
    image: edoburu/pgbouncer:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "15432:5432"
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.110
    volumes:
      - ./pgbouncer/pgbouncer_pwd.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
      - ./certs:/certs:ro
networks:
  nofrillsdb-network:
    external: true
volumes:
  pgdata:
