services:
  fluentd:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ENDPOINT=${ENDPOINT}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf:ro
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.100
networks:
  nofrillsdb-network:
    external: true