services:
  nofrillsdb-frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${SECURE_PORT}:${SECURE_PORT}"
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - PORT=${PORT}
      - SECURE_PORT=${SECURE_PORT}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.1.100:24224"
        tag: "nofrillsdb.frontend"
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.10
  nofrillsdb-backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    depends_on:
      - nofrillsdb-redis
    ports:
      - "8443:8443"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.1.100:24224"
        tag: "nofrillsdb.backend"
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.102
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
  nofrillsdb-database:
    build:
      context: ../postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: nofrillsdb
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nofrillsdb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - prod_nofrillsdb_database:/var/lib/postgresql/data
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.101
    ports:
      - "5432:5432"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.1.100:24224"
        tag: "nofrillsdb.database"
networks:
  nofrillsdb-network:
    external: true
volumes:
  prod_nofrillsdb_database:
    external: true
