services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.1.100:24224"
        tag: "nofrillsdb.caddy"
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.11
    depends_on:
      - nofrillsdb-frontend

  nofrillsdb-frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
        VITE_AUTH0_REDIRECT_URL: ${VITE_AUTH0_REDIRECT_URL}
        VITE_JDBC_PWD_ENDPOINT: ${VITE_JDBC_PWD_ENDPOINT}
        VITE_JDBC_CRT_ENDPOINT: ${VITE_JDBC_CRT_ENDPOINT}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
        PORT: ${PORT}
    expose:
      - "${PORT}"
    environment:
      - PORT=${PORT}
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
      - VITE_AUTH0_REDIRECT_URL=${VITE_AUTH0_REDIRECT_URL}
      - VITE_JDBC_PWD_ENDPOINT=${VITE_JDBC_PWD_ENDPOINT}
      - VITE_JDBC_CRT_ENDPOINT=${VITE_JDBC_CRT_ENDPOINT}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.1.100:24224"
        tag: "nofrillsdb.frontend"
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.10

  nofrillsdb-backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    # âœ… remove public port; keep internal only
    expose:
      - "8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.1.100:24224"
        tag: "nofrillsdb.backend"
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.102
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  nofrillsdb-database:
    build:
      context: ../postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: nofrillsdb
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nofrillsdb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - prod_nofrillsdb_database:/var/lib/postgresql/data
    networks:
      nofrillsdb-network:
        ipv4_address: 172.28.1.101
    ports:
      - "127.0.0.1:5432:5432"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.1.100:24224"
        tag: "nofrillsdb.database"

networks:
  nofrillsdb-network:
    external: true

volumes:
  prod_nofrillsdb_database:
    external: true
  caddy_data:
  caddy_config: