spring:
  datasource:
    username: nofrillsdb
    password: ${PROD_DB_PASSWORD:}
    url: jdbc:postgresql://nofrillsdb-database:5432/nofrillsdb
    driver-class-name: org.postgresql.Driver
provisioning:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://nofrillsdb-database:5432/nofrillsdb
    username: provisioner
    password: ${PROVISIONER_DB_PASSWORD:}
  client-ca-key: ${CLIENT_CA_KEY}
  client-ca-crt-location: certs/public_clients_ca.crt
  connection-limit: 20
  statement-timeout: 10s
  pool-user: pgbouncer_auth