spring:
  datasource:
    username: vinayakr
    password: ""
    url: jdbc:postgresql://localhost:5432/nofrillsdb
    driver-class-name: org.postgresql.Driver
provisioning:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres
    username: provisioner
    password: ${DEV_PROVISIONER_DB_PASSWORD:}
  client-ca-key: ${DEV_CLIENT_CA_KEY}
  client-ca-crt-location: certs/clients_ca.crt
  connection-limit: 20
  statement-timeout: 10s
  pool-user: pgbouncer_auth
stripe:
  secret-key: ${DEV_STRIPE_SECRET_KEY:}
